// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: edADxkrxNS9ND5YewKEz7S
// Component: 7IYBOX209oVC

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_build_systems_webseite.module.css"; // plasmic-import: edADxkrxNS9ND5YewKEz7S/projectcss
import sty from "./PlasmicButtonExternalLink.module.css"; // plasmic-import: 7IYBOX209oVC/css

createPlasmicElementProxy;

export type PlasmicButtonExternalLink__VariantMembers = {};
export type PlasmicButtonExternalLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicButtonExternalLink__VariantsArgs;
export const PlasmicButtonExternalLink__VariantProps =
  new Array<VariantPropType>();

export type PlasmicButtonExternalLink__ArgsType = {
  children?: React.ReactNode;
  link?: string;
};
type ArgPropType = keyof PlasmicButtonExternalLink__ArgsType;
export const PlasmicButtonExternalLink__ArgProps = new Array<ArgPropType>(
  "children",
  "link"
);

export type PlasmicButtonExternalLink__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultButtonExternalLinkProps {
  children?: React.ReactNode;
  link?: string;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicButtonExternalLink__RenderFunc(props: {
  variants: PlasmicButtonExternalLink__VariantsArgs;
  args: PlasmicButtonExternalLink__ArgsType;
  overrides: PlasmicButtonExternalLink__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        <p.PlasmicLink
          data-plasmic-name={"link"}
          data-plasmic-override={overrides.link}
          className={classNames(projectcss.all, projectcss.a, sty.link)}
          component={Link}
          href={args.link}
          platform={"nextjs"}
          target={"_blank"}
        >
          {p.renderPlasmicSlot({
            defaultContents: "Some link text",
            value: args.children,
            className: classNames(sty.slotTargetChildren)
          })}
        </p.PlasmicLink>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "link"],
  freeBox: ["freeBox", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicButtonExternalLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicButtonExternalLink__VariantsArgs;
    args?: PlasmicButtonExternalLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicButtonExternalLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicButtonExternalLink__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicButtonExternalLink__ArgProps,
          internalVariantPropNames: PlasmicButtonExternalLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicButtonExternalLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicButtonExternalLink";
  } else {
    func.displayName = `PlasmicButtonExternalLink.${nodeName}`;
  }
  return func;
}

export const PlasmicButtonExternalLink = Object.assign(
  // Top-level PlasmicButtonExternalLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicButtonExternalLink
    internalVariantProps: PlasmicButtonExternalLink__VariantProps,
    internalArgProps: PlasmicButtonExternalLink__ArgProps
  }
);

export default PlasmicButtonExternalLink;
/* prettier-ignore-end */
