// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: edADxkrxNS9ND5YewKEz7S
// Component: JmuJs7xkzhfG

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import ButtonExternalLink from "../../ButtonExternalLink"; // plasmic-import: 7IYBOX209oVC/component
import Footer from "../../Footer"; // plasmic-import: XG5TargEes9F/component

import { useScreenVariants as useScreenVariants_5XwAguWqqS0 } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 5XW-aguWqqS0/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_build_systems_webseite.module.css"; // plasmic-import: edADxkrxNS9ND5YewKEz7S/projectcss
import sty from "./PlasmicImageFooter.module.css"; // plasmic-import: JmuJs7xkzhfG/css

createPlasmicElementProxy;

export type PlasmicImageFooter__VariantMembers = {};
export type PlasmicImageFooter__VariantsArgs = {};
type VariantPropType = keyof PlasmicImageFooter__VariantsArgs;
export const PlasmicImageFooter__VariantProps = new Array<VariantPropType>();

export type PlasmicImageFooter__ArgsType = {};
type ArgPropType = keyof PlasmicImageFooter__ArgsType;
export const PlasmicImageFooter__ArgProps = new Array<ArgPropType>();

export type PlasmicImageFooter__OverridesType = {
  root?: p.Flex<"div">;
  img?: p.Flex<typeof p.PlasmicImg>;
  footer?: p.Flex<typeof Footer>;
};

export interface DefaultImageFooterProps {
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicImageFooter__RenderFunc(props: {
  variants: PlasmicImageFooter__VariantsArgs;
  args: PlasmicImageFooter__ArgsType;
  overrides: PlasmicImageFooter__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_5XwAguWqqS0()
  });

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        ``
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__zs8P6)}>
        <p.PlasmicImg
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"1068px"}
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"100%"}
          src={{
            src: "/plasmic/build_systems_webseite/images/desktopRenderingjpg.jpg",
            fullWidth: 3146,
            fullHeight: 2000,
            aspectRatio: undefined
          }}
        />

        <div className={classNames(projectcss.all, sty.freeBox__hOcJf)} />

        <div className={classNames(projectcss.all, sty.freeBox___9Mx1S)}>
          <div className={classNames(projectcss.all, sty.freeBox__w8WwD)}>
            <div className={classNames(projectcss.all, sty.freeBox___6LcI4)}>
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__fsnym
                )}
              >
                {"Sie haben weitere Fragen?"}
              </div>
            </div>
            <ButtonExternalLink
              className={classNames(
                "__wab_instance",
                sty.buttonExternalLink__jnq78
              )}
              link={"mailto:mail@buildsystems.de"}
            >
              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__rrSbk
                )}
              >
                {"Schreiben Sie uns eine Mail!"}
              </div>
            </ButtonExternalLink>
            <ButtonExternalLink
              className={classNames(
                "__wab_instance",
                sty.buttonExternalLink__bFFkm
              )}
              link={
                "https://drive.google.com/uc?export=download&id=16NF9t3tM6m2UBnFR17JmBRj5XsAov-JN"
              }
            >
              {"      Download Leistungen       "}
            </ButtonExternalLink>
            <ButtonExternalLink
              className={classNames(
                "__wab_instance",
                sty.buttonExternalLink___28Prb
              )}
              link={
                "https://drive.google.com/uc?export=download&id=1wud4OftAcf2hM0p6Ca0UWxNUcTeSYIci"
              }
            >
              {"       Sneak Peak Roadmap      "}
            </ButtonExternalLink>
          </div>
        </div>
      </div>
      <Footer
        data-plasmic-name={"footer"}
        data-plasmic-override={overrides.footer}
        className={classNames("__wab_instance", sty.footer)}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "img", "footer"],
  img: ["img"],
  footer: ["footer"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  img: typeof p.PlasmicImg;
  footer: typeof Footer;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicImageFooter__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicImageFooter__VariantsArgs;
    args?: PlasmicImageFooter__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicImageFooter__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicImageFooter__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicImageFooter__ArgProps,
          internalVariantPropNames: PlasmicImageFooter__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicImageFooter__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicImageFooter";
  } else {
    func.displayName = `PlasmicImageFooter.${nodeName}`;
  }
  return func;
}

export const PlasmicImageFooter = Object.assign(
  // Top-level PlasmicImageFooter renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    footer: makeNodeComponent("footer"),

    // Metadata about props expected for PlasmicImageFooter
    internalVariantProps: PlasmicImageFooter__VariantProps,
    internalArgProps: PlasmicImageFooter__ArgProps
  }
);

export default PlasmicImageFooter;
/* prettier-ignore-end */
