// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: edADxkrxNS9ND5YewKEz7S
// Component: EF175LjqiU3X

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/react-web/lib/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_build_systems_webseite.module.css"; // plasmic-import: edADxkrxNS9ND5YewKEz7S/projectcss
import sty from "./PlasmicOldButtonExternalLink.module.css"; // plasmic-import: EF175LjqiU3X/css

createPlasmicElementProxy;

export type PlasmicOldButtonExternalLink__VariantMembers = {};
export type PlasmicOldButtonExternalLink__VariantsArgs = {};
type VariantPropType = keyof PlasmicOldButtonExternalLink__VariantsArgs;
export const PlasmicOldButtonExternalLink__VariantProps =
  new Array<VariantPropType>();

export type PlasmicOldButtonExternalLink__ArgsType = {
  destinationLink?: string;
  children?: React.ReactNode;
};
type ArgPropType = keyof PlasmicOldButtonExternalLink__ArgsType;
export const PlasmicOldButtonExternalLink__ArgProps = new Array<ArgPropType>(
  "destinationLink",
  "children"
);

export type PlasmicOldButtonExternalLink__OverridesType = {
  root?: p.Flex<"div">;
  link?: p.Flex<"a"> & Partial<LinkProps>;
};

export interface DefaultOldButtonExternalLinkProps {
  destinationLink?: string;
  children?: React.ReactNode;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicOldButtonExternalLink__RenderFunc(props: {
  variants: PlasmicOldButtonExternalLink__VariantsArgs;
  args: PlasmicOldButtonExternalLink__ArgsType;
  overrides: PlasmicOldButtonExternalLink__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();
  const $ctx = ph.useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const currentUser = p.useCurrentUser?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <p.PlasmicLink
        data-plasmic-name={"link"}
        data-plasmic-override={overrides.link}
        className={classNames(projectcss.all, projectcss.a, sty.link)}
        component={Link}
        href={args.destinationLink}
        platform={"nextjs"}
        target={"_blank"}
      >
        {p.renderPlasmicSlot({
          defaultContents: "Action",
          value: args.children,
          className: classNames(sty.slotTargetChildren)
        })}
      </p.PlasmicLink>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "link"],
  link: ["link"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  link: "a";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicOldButtonExternalLink__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicOldButtonExternalLink__VariantsArgs;
    args?: PlasmicOldButtonExternalLink__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicOldButtonExternalLink__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    /* Specify args directly as props*/ Omit<
      PlasmicOldButtonExternalLink__ArgsType,
      ReservedPropsType
    > &
    /* Specify overrides for each element directly as props*/ Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    /* Specify props for the root element*/ Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicOldButtonExternalLink__ArgProps,
          internalVariantPropNames: PlasmicOldButtonExternalLink__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicOldButtonExternalLink__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOldButtonExternalLink";
  } else {
    func.displayName = `PlasmicOldButtonExternalLink.${nodeName}`;
  }
  return func;
}

export const PlasmicOldButtonExternalLink = Object.assign(
  // Top-level PlasmicOldButtonExternalLink renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    link: makeNodeComponent("link"),

    // Metadata about props expected for PlasmicOldButtonExternalLink
    internalVariantProps: PlasmicOldButtonExternalLink__VariantProps,
    internalArgProps: PlasmicOldButtonExternalLink__ArgProps
  }
);

export default PlasmicOldButtonExternalLink;
/* prettier-ignore-end */
